application: nh-local-reviews-agente
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers match in order, put above the default handler.
handlers:
- url: /favicon\.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: assets/stylesheets/\1
  upload: assets/stylesheets/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: assets/javascript/\1
  upload: assets/javascript/(.*\.js)

# site root
- url: /
  static_files: assets/templates/main.html
  upload: assets/templates/main.html
